### PR TITLE
Release 2.4.4.1+carto-1

### PR DESCRIPTION
**Pull request by Algunenano**
I've tested PG11, 10.4 and 9.5 and all tests are passing.

Closes https://github.com/CartoDB/postgis/issues/13

### CODE REVIEW

**Review by rafatower — COMMENTED** [review]
I don't quite understand this PR. I don't see the merge of the community branch and the `POSTGIS_MICRO_VERSION` rewinded from 5 to 4.

Most likely I missed some of your work in between.

Once the new package are ready, we'd need to notify Infrastructure to roll out it, at least for new and migrated machines (or better for all of them if there are no changes in sql scripts / c api).

**Comment by Algunenano** [comment]
The changes were brought in https://github.com/CartoDB/postgis/pull/14.

I changed from 2.4.5 to 2.4.4 because 2.4.4 hasn't been released officially yet, but I could go either way.

**Comment by rafatower** [comment]
Uhm, I see this is the merge: https://github.com/CartoDB/postgis/pull/14

**Review by rafatower — APPROVED** [review]
I haven't reviewed the merge itself but I trust your git kung-fu and the little fixes

(don't we have a ticket to set up a test matrix somewhere?)

**Comment by Algunenano** [comment]
Merging this and I'll try to setup the matrix with our PG releases doing a release.

**Pull request merged**
