### PR TITLE
Backport TWKB to 2.1

### PR DESCRIPTION
**Pull request by pramsey**

### CODE REVIEW

**Comment by javisantana** [comment]
One of my main concerns is that the postgis extension transition is smooth, not sure how the 2.1.8 -> 2.1.8.cdb would be and specially how 2.1.8.cdb -> 2.2.0 will be done. Will be have collision problems with function signatures? will we need to do special migration?

**Comment by pramsey** [comment]
My plan is to piconumber them, so 2.1.8.1, and so on. Question is if we are willing to bet we won't have script changes only dll changes. If so we leave the extension version numbers alone and only change the dll version number, for tracking purposes.

P.

**Comment by pramsey** [comment]
@rochoa, @zenitraM thoughts and review on this?

**Comment by zenitraM** [comment]
+1 to @javisantana: won't we need to add new scripts to add the TWKB functions?

**Comment by pramsey** [comment]
OK, per @zenitraM's notes on the fact that, oops yeah, we have three new function signatures (`ST_AsTWKB(geom)`, `ST_GeomFromTWKB(bytea)`, and `ST_AsTWKB(geom[], int[])`) just sliding a new library underneath isn't going to cut it as we backport whole new features. So, the implication is that the CDB ultra-minor version number floats upwards, into the extension version, and we have to run the full `ALTER EXTENSION UPDATE` process.

Once we start advertising our version number in the extension, we get onto the extension management train and it's hard to get off. The actual code for doing 2.1.8.2 to 2.2.0 migrations wouldn't be bad, since it's all `CREATE OR REPLACE FUNCTION` stuff that overlays just fine. The problem will be that it will not be possible to directly upgrade from 2.1.8.1 to 2.2.0, since the generic 2.2.0 package won't have an upgrade path from our microversion to the new version. (It'll have 2.1.8 -> 2.2.0 but not 2.1.8.2 -> 2.2.0). So in order to move to 2.2.0 we'd have to first cut our own custom version that includes the upgrade path we need.

Another option would be to stick the function signatures we need into their own extension (postgis-cartodb) with its own version. They would require that a new version of the DLL be present (so they have somewhere to bind) but at least then the extension version number of postgis would stay generic.

Then the update to 2.2.0 would be something like 
- install the postgis-2.2.0 debian package
- `DROP EXTENSION postgis-cartodb` and 
- `ALTER EXTENSION postgis UPDATE TO '2.2.0'`

And updates to back-port new functionality would be something like
- install the postgis-2.1.8.4 debian package
- if there are no new function signatures, you're done
- if there **are** new functions, then `ALTER EXTENSION postgis-cartodb UPDATE TO '2.1.8.4'`
- postgis extension version is just 2.1.8 and doesn't change through these updates

Thoughts?

**Comment by rochoa** [comment]
Just to be clear, your proposal is to have postgis-cartodb as an extension to postgis, so we isolate backported functions there to avoid issues with upgrade path, right?

**Comment by zenitraM** [comment]
Another option (hacky) could be updating `pg_extension` manually before upgrading to 2.2.0 to indicate it is 2.1.8 really.

How is `postgis_topology` handled? - even though it probably doesn't have the logic to keep a separate version/microversion

**Comment by pramsey** [comment]
Yes, the idea is that you would `CREATE EXTENSION postgis` and then `CREATE EXTENSION postgis-cartodb` to add the extra functions. `postgis-cartodb` would be a SQL-only extension that depends on the `postgis` extension (for another example, see the `pointcloud_postgis` [extension](https://github.com/pgpointcloud/pointcloud/tree/master/pgsql_postgis) that depends on both the `postgis` and `pointcloud` extensions.

**Comment by pramsey** [comment]
Looks like `postgis_topology` just shares a version number with `postgis`. Unfortunately (or maybe, given the potential added complexity, fortunately), at this moment extensions don't do dependencies on particular _versions_ of extensions, just on the extension name itself. So `postgis_topology` won't check that the `postgis` it depends on is of a particular version.

**Comment by pramsey** [comment]
Regards your hacky approach, @zenitraM, it has a certain appeal, but one upside of the add-on extension approach is that it allows the silent fixing of bugs without full extension upgrade (just install new postgis-2.1.8.x deb package). Once we add our minor number to the extension number, then even small updates require full extension upgrade. Or the addition of **two** version numbers, one to increment for silent DLL updates and one to increment for function updates.

**Comment by zenitraM** [comment]
Another (again, even more hacky) approach could be adding the signatures of those functions to `cartodb-postgresql`, would it be feasible?

They would live on the `cartodb` schema instead of the `public` schema - so PostGIS functions (once present) would shadow them.

Anyway the place where breaking the extension rail will cause more trouble is OSS installs - in our controlled environment we can just copy the `2.1.8-to-2.2.0` sql to `2.1.8.1-to-2.2.0` and run the `ALTER`, but it's a bit more difficult to explain you need to do that to users

**Comment by pramsey** [comment]
I was thinking of managing the `postgis_cartodb` extension inside our custom repo, and I think that is less brittle than having them inside cartodb-postgresql. My concern about cartodb-postgresql is that we then link the version of that extension to the postgis version, which increases version management pain. All in all though, there will be some pain here...

**Comment by zenitraM** [comment]
The problem with handling `postgis_cartodb` on its own repo is that, unless we completely separate the backported features, it will still depend on a specific commit (or range or commits) from this repo...

What about creating them from this repo, but outputting them into a separate, third extension called `postgis_backport` (à la PostGIS-topology)?

`postgis_backport` extension version could include the micro version (or even have a different version) while PostGIS itself would not.

**Comment by pramsey** [comment]
What you have proposed is what I'm proposing too. `./extensions/postgis_backport` inside our `svn-2.1-cartodb` branch.

I think it should have its own version, completely different from postgis version, otherwise we'll end up with strange situations where the .deb package has version 2.1.8.3, the postgis extension is 2.1.8 and the backport extension version is 2.1.8.2. Or, if the backport version tracked the .deb version, we'd end up skipping applying it most of the time, when changes to the .deb don't includes changes to the backport functions.

Thoughts on what version number the postgis_backport should advertise?

**Comment by zenitraM** [comment]
(a related interesting fact I didn't know:

ALTER EXTENSION is able to execute sequences of update script files to achieve a requested update. For example, if only foo--1.0--1.1.sql and foo--1.1--2.0.sql are available, ALTER EXTENSION will apply them in sequence if an update to version 2.0 is requested when 1.0 is currently installed.

So if we went with 2.1.8.1 and we add in a `postgis--2.1.8.1--2.1.8.sql` which drops the 2.1.8.1 functions while upgrading to 2.2.0, it seems like postgres _might_ be able to follow the `2.1.8.1 -> 2.1.8 -> 2.2.0` route.)

**Comment by zenitraM** [comment]
I'd say, make it a different, unrelated version and let's only change it when we change SQL signatures.

**Comment by pramsey** [comment]
I really really like your trick w/ extension numbers... I think that warrants testing, I bet it would work. (version "numbers" aren't actually numbers in extension, so you can traverse them in any order you want, as long as a path is found... Oh, except in return for that cleanliness we _would_ have to accept doing a full db upgrade for every version bump, even when the version doesn't include any SQL changes.

**Comment by zenitraM** [comment]
yup, it seems it works after creating an empty upgrade path to and from 2.1.8.1:

```
foobardo=# select * from pg_extension_update_paths('postgis') where source='2.1.8' and path is not null;
 source |  target   |       path
--------+-----------+------------------
 2.1.8  | 2.1.8next | 2.1.8--2.1.8next
 2.1.8  | 2.1.8.1   | 2.1.8--2.1.8.1
(2 rows)

foobardo=# select * from pg_extension_update_paths('postgis') where source='2.1.8.1' and path is not null;
 source  |  target   |           path
---------+-----------+---------------------------
 2.1.8.1 | 2.1.8next | 2.1.8.1--2.1.8--2.1.8next
 2.1.8.1 | 2.1.8     | 2.1.8.1--2.1.8
(2 rows)
```

Some interesting applications for sure

**Comment by pramsey** [comment]
OK, so final answer? 
- `postgis_backport` extension living in the `svn-2.1-cartodb` postgis branch extension but w/ independent version number? or,
- Explicit `2.1.8.x` versioning with full extension upgrade path on each micropatch release?

**Comment by rochoa** [comment]
I would go with the simpler solution, in this case I think it's easier to understand the separated extension approach and I guess it's better to not being smart about version numbers and upgrade paths. But I'm not the expert here :wink:

**Comment by zenitraM** [comment]
I'd say `postgis_backport` too, sounds cleaner and avoids diverging much from PostGIS

**Comment by pramsey** [comment]
ok, thy will be done (in an hour or so)

**Comment by pramsey** [comment]
OK, so there is now a postgis_backport extension.

The .deb packaging will need to make sure it picks it up (presumably the rules for the extension directory are just globs, so perhaps it'll just automagically happen).

In order for the TWKB functions to work now, the postgis stuff has to be installed, and the postgis_backport also installed. I've started the postgis_backport version at `2.1a` and will increment it lexically as more functions are added.

This is certainly not quite as elegant as having everything remain inside the postgis extension and adding upgrade rules for 2.2.0, but it does work.

**Comment by zenitraM** [comment]
Okay, so shall we now merge both PRs and build from there?

**Pull request merged**
